import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Gallery",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico", // явное указание пути от корня public/app
    },
};

// 1. Добавили async, чтобы работал await внутри
export default async function RootLayout({
                                             children,
                                             params, // 2. Принимаем params как аргумент функции
                                         }: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>; // Типизация для params
}>) {
    // Теперь await отработает без ошибок!
    const { locale } = await params;

    // Проверяем, что эта локаль поддерживается (ru или en), иначе отдаем 404
    if (!routing.locales.includes(locale as any)) {
        notFound();
    }

    // Загружаем JSON-файлы переводов для этой локали на сервере
    const messages = await getMessages();

    return (
        // 3. Заменили жестко прописанный lang="en" на динамический lang={local}
        <html
            lang={locale}
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col bg-neutral-950 text-white">
        {/* Провайдер успешно раздает контекст переводов */}
        <NextIntlClientProvider messages={messages}>
            {children}
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
